language: java
sudo: false
install: true
jdk:
  - oraclejdk8
addons:
  sonarcloud:
    organization: "tech-advantage"
    token:
      secure: "ToC1PTHu8r2wuqzGlkNOJ8LSyVbB4jGpcf7/9BceLhGFFjjqH6u0F+/gpUNrG1MroXf8vdm4G9dp3CKZ4b4FlCJ5nYDq/mO+m8xE6SGW8veNknf17iQqtTKhA6ruFqv2xDbREf1jFkZPOEGBc8+6qWjGf8/2piu/Ef6paQoO+r0="
script:
  - mvn -Dsonar.host.url=https://sonarcloud.io clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

